### ISSUE TITLE
[BUG]    Links to PRs, Merged PRs, and Issues detail no longer works

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Opensource-Contribution-Leaderboard#55]
This is a major regression.

The links to PRs, Merged PRs, and Issues detail now REQUIRE the user to be logged onto Github to work.

This is unacceptable.

Any user, even those without Github account, should be able to view the details of these links.   It will require some caching of the information.

One workable compromise might be to:
1) detect if user is logged onto Github 
2) only display clickable link if logged on; otherwise display static count only

**Comment by djcruz93** [comment]
@Sing-Li I'll take this up. Actually earlier the URL used for searching was https://github.com/pulls?q=is:pr+org:RocketChat+author:Darshilp326+is:open+created:%3E=2020-11-20 which required the user to logged in in order to work.
Changing it to https://github.com/search?q=type:pr+org:RocketChat+author:Darshilp326+is:open+created:%3E=2020-11-20 will work for all types of users.
**Note** I have changed the URL from **pulls** to **search** and query param from **is:pr** to **type:pr**
Screenshots:
![image](https://user-images.githubusercontent.com/51796498/104124630-e3068100-5377-11eb-86db-04df2ce2d056.png)
